// Printable client-facing quote. Clean A4-ish layout; the browser's print
// dialog produces the PDF. No app chrome. Reads through loadQuoteDetail so it
// renders from Postgres or Airtable behind the migration flag.

import { notFound } from "next/navigation";
import { OrgLogo } from "@/components/OrgLogo";
import { currency, formatDate } from "@/lib/format";
import { loadQuoteDetail } from "@/lib/platform/quoteDetailSource";
import { requireOrgCtx } from "@/lib/platform/org-context";

export const dynamic = "force-dynamic";

export default async function QuotePrintPage({
  params,
}: {
  params: Promise<{ org: string; id: string }>;
}) {
  const { org, id } = await params;
  const ctx = await requireOrgCtx(org);
  const quote = await loadQuoteDetail(ctx, id);
  if (!quote) notFound();

  const projectLocation =
    [quote.jobAddress, quote.jobSuburb].filter(Boolean).join(", ") || quote.jobCode;

  return (
    <div className="bg-white min-h-screen text-neutral-900">
      <div className="max-w-3xl mx-auto p-8">
        <div className="flex justify-between items-start border-b-2 border-[var(--ae-space,#dc9f82)] pb-4 mb-6">
          <div className="flex items-center gap-3">
            <OrgLogo logo={ctx.config.branding?.logo} name={ctx.orgName} size={48} />
            <div>
              <div className="text-2xl font-bold" style={{ color: "var(--ae-space, #dc9f82)" }}>
                {ctx.orgName}
              </div>
              <div className="text-sm text-neutral-500">Quotation</div>
            </div>
          </div>
          <div className="text-right text-sm">
            <div className="font-mono font-semibold">{quote.refNumber}</div>
            {quote.createdAt && <div className="text-neutral-500">{formatDate(quote.createdAt)}</div>}
            {quote.validUntil && (
              <div className="text-neutral-500">Valid until {formatDate(quote.validUntil)}</div>
            )}
          </div>
        </div>

        <div className="grid grid-cols-2 gap-6 mb-6 text-sm">
          <div>
            <div className="text-xs uppercase tracking-wide text-neutral-400 mb-1">Quote for</div>
            <div className="font-semibold">{quote.clientName || "—"}</div>
            <div className="text-neutral-600">{quote.title}</div>
          </div>
          <div>
            <div className="text-xs uppercase tracking-wide text-neutral-400 mb-1">Project</div>
            <div className="font-semibold">{quote.jobName}</div>
            <div className="text-neutral-600">{projectLocation}</div>
          </div>
        </div>

        <table className="w-full text-sm mb-6">
          <thead>
            <tr className="border-b border-neutral-300 text-left text-xs text-neutral-500">
              <th className="py-2">Description</th>
              <th className="py-2 text-right w-12 pr-3">Qty</th>
              <th className="py-2 w-16">Unit</th>
              <th className="py-2 text-right w-28">Unit price</th>
              <th className="py-2 text-right w-28">Amount</th>
            </tr>
          </thead>
          <tbody>
            {quote.lines.map((l) => (
              <tr key={l.id} className="border-b border-neutral-100">
                <td className="py-2">
                  {l.description}
                  {l.category ? <span className="block text-xs text-neutral-400">{l.category}</span> : null}
                </td>
                <td className="py-2 text-right pr-3">{l.qty}</td>
                <td className="py-2">{l.unit}</td>
                <td className="py-2 text-right whitespace-nowrap">{currency(l.unitPrice)}</td>
                <td className="py-2 text-right whitespace-nowrap">{currency(l.lineTotal)}</td>
              </tr>
            ))}
          </tbody>
        </table>

        <div className="flex justify-end mb-8">
          <div className="w-64 text-sm">
            <div className="flex justify-between py-1">
              <span className="text-neutral-600">Subtotal</span>
              <span>{currency(quote.subtotal)}</span>
            </div>
            <div className="flex justify-between py-1">
              <span className="text-neutral-600">GST ({quote.gstRate}%)</span>
              <span>{currency(quote.gstAmount)}</span>
            </div>
            <div className="flex justify-between py-2 border-t-2 border-neutral-800 font-bold text-base">
              <span>Total (inc GST)</span>
              <span>{currency(quote.total)}</span>
            </div>
          </div>
        </div>

        {quote.notes && (
          <div className="text-sm border-t border-neutral-200 pt-4">
            <div className="text-xs uppercase tracking-wide text-neutral-400 mb-1">Notes &amp; terms</div>
            <p className="whitespace-pre-wrap text-neutral-700">{quote.notes}</p>
          </div>
        )}

        <p className="text-xs text-neutral-400 mt-8 text-center">
          {quote.refNumber} · Generated by {ctx.orgName} · All amounts in AUD.
        </p>
      </div>
    </div>
  );
}
