// AUTO-GENERATED from base appharWaojouHgMeW via the Airtable meta API.
// Source of truth for Core table/field IDs. Regenerate, do not hand-edit:
//   node scripts/airtable-gen-schema.mjs

export const CORE_SCHEMA = {
  ORGANISATIONS: {
    tableId: "tblhkggy89SSAjF2y",
    fields: [
      { name: "Organisation_Name", id: "fldMbFDVU01DYPnnj", type: "singleLineText" },
      { name: "Notes", id: "fldbSvrybSPNpEggA", type: "multilineText" },
      { name: "_TIER", id: "fldBdmCnujaBssKOm", type: "singleLineText" },
      { name: "Type", id: "fld7Ro0t4WVVe1wz0", type: "singleSelect" },
      { name: "Org_Status", id: "fldJrpsQRzgVOaAG5", type: "singleSelect" },
      { name: "Website", id: "fld3w41jEf6POPfmn", type: "url" },
      { name: "Industry", id: "fldP0cROxhdEOu9sa", type: "singleLineText" },
      { name: "CONTACTS", id: "fldU8Ba1i5U9fO8qc", type: "multipleRecordLinks" },
      { name: "WORKSTREAMS", id: "fld8j7wXVqDU6w6E7", type: "multipleRecordLinks" },
      { name: "PRICING", id: "fldKBBMYXQbBo31z3", type: "multipleRecordLinks" },
      { name: "TEAM", id: "fldZE6NEoQUzfi2Ul", type: "multipleRecordLinks" },
    ],
  },
  CONTACTS: {
    tableId: "tbl6xGpm3iDdMKzyB",
    fields: [
      { name: "Contact_Name", id: "fldviJRo4TY1PXCpH", type: "singleLineText" },
      { name: "First_Name", id: "fldnMUHvXq4T1aaWW", type: "singleLineText" },
      { name: "Last_Name", id: "fldPIU5fBUpspclb2", type: "singleLineText" },
      { name: "Email", id: "fldmjcyBjfsi96NYd", type: "email" },
      { name: "Phone", id: "fldVPzJEALOZm5UAK", type: "phoneNumber" },
      { name: "Organisation", id: "fldJcXYnJ4ECXJVdw", type: "multipleRecordLinks" },
      { name: "Role", id: "fldWpNiRBTTSR2kuf", type: "singleLineText" },
      { name: "LinkedIn", id: "fld8CT01YwLXn3LPk", type: "url" },
      { name: "Notes", id: "fld4mtZNWgGLAGlPG", type: "multilineText" },
      { name: "_TIER", id: "fldmE3V8ubNlcEHZd", type: "singleLineText" },
    ],
  },
  WORKSTREAMS: {
    tableId: "tbl3akARszuLzfA8M",
    fields: [
      { name: "Workstream_Name", id: "fldXO2l1fi60Djxud", type: "singleLineText" },
      { name: "Description", id: "fldraZjmwECIdAwqR", type: "multilineText" },
      { name: "Lead", id: "fldimVNEJtj2KjrN2", type: "multipleRecordLinks" },
      { name: "Status", id: "fldbgKQdSzaPjEQKk", type: "singleSelect" },
      { name: "Organisation", id: "fldcDksaDaIG4OmYw", type: "multipleRecordLinks" },
      { name: "Priority", id: "fldQHQQItXvQ1vQba", type: "singleSelect" },
      { name: "DECISIONS", id: "fld4bnSe4Kk22XMvu", type: "multipleRecordLinks" },
      { name: "EXECUTION_LOG", id: "fldAMoTbnfJcCdMmZ", type: "multipleRecordLinks" },
      { name: "JOBS", id: "fldxRFfEC5XPRND5Y", type: "multipleRecordLinks" },
      { name: "HYPOTHESES", id: "fldFmgfT90QEkwRE8", type: "multipleRecordLinks" },
      { name: "DOCUMENTS", id: "fldDXvh6oXdgC7tiW", type: "multipleRecordLinks" },
      { name: "INTELLIGENCE_SNAPSHOT", id: "fldCcBf42v2OO7U9V", type: "multipleRecordLinks" },
      { name: "_TIER", id: "fldJg1GfM9pZAzWkx", type: "singleLineText" },
      { name: "Track", id: "fldofbycTBStNsn0r", type: "singleSelect" },
      { name: "Start_Date", id: "fldV0sc2QY7HrLHMb", type: "date" },
      { name: "Target_Date", id: "fldplOKodCiTtipIh", type: "date" },
      { name: "Current_State", id: "fldA1Bka4VDigqaU4", type: "multilineText" },
      { name: "Next_Milestone", id: "fldyiGITGcZvIoNlg", type: "multilineText" },
    ],
  },
  DECISIONS: {
    tableId: "tblsHgiXa0Efo3IWD",
    fields: [
      { name: "Decision_Name", id: "fldIDXimKr7PBC41e", type: "singleLineText" },
      { name: "Decision_Description", id: "fldz30kBm8F3cyeG6", type: "multilineText" },
      { name: "Related_Workstream", id: "fldkhlCg4wEAq9Fs3", type: "multipleRecordLinks" },
      { name: "Decision_Date", id: "fldtrM1uTnlpf88Si", type: "dateTime" },
      { name: "Owner", id: "fldBnBOU8MG66EW2z", type: "multipleRecordLinks" },
      { name: "Status", id: "fldvggciokLYyx5FQ", type: "singleSelect" },
      { name: "Notes", id: "fld9Bd0Q9I4aHdhcY", type: "multilineText" },
      { name: "ACTION_HUB", id: "fldcbxS44JV1C8ntZ", type: "multipleRecordLinks" },
      { name: "_TIER", id: "fldACe62pelNf1cjp", type: "singleLineText" },
      { name: "Decision_Type", id: "fldFyep7Zdj1TyGB5", type: "singleSelect" },
      { name: "Reversibility", id: "fldm5JcGXHe6nmn0R", type: "singleSelect" },
      { name: "Confidence", id: "fldIWCQyuCuh1SKW0", type: "number" },
      { name: "Context", id: "fldoDHCBl7JvmLZoT", type: "multilineText" },
      { name: "Decision_Made", id: "fldJvJU0acmJOI5GP", type: "multilineText" },
      { name: "Alternatives_Rejected", id: "fld6bddEWs7EQHqGp", type: "multilineText" },
      { name: "Rationale", id: "fldXH5tHvUC8RpuCi", type: "multilineText" },
      { name: "Domain", id: "fldQOD6FVY3WY2lCV", type: "singleLineText" },
    ],
  },
  ACTION_HUB: {
    tableId: "tblndF30LVZaHcFug",
    fields: [
      { name: "Action_Name", id: "fldNdCN0KE8ehUrHl", type: "singleLineText" },
      { name: "Description", id: "fldoGrF1qHXEVDwai", type: "multilineText" },
      { name: "Assigned_To", id: "fldZr1TGqRZ90J5jL", type: "multipleRecordLinks" },
      { name: "Due_Date", id: "fldSlWTZpxwpowc6f", type: "dateTime" },
      { name: "Status", id: "fldNrrOJDfZXb6Fzu", type: "singleSelect" },
      { name: "Linked_Decision", id: "fldZHG0j7Uv7A0xFr", type: "multipleRecordLinks" },
      { name: "Priority", id: "fldYXAZHXVK4ny8jP", type: "singleSelect" },
      { name: "_TIER", id: "fldrkJBZYILNxBq9J", type: "singleLineText" },
      { name: "Trigger_Condition", id: "fld6AKpHaHCmUIM1x", type: "multilineText" },
      { name: "Completion_Date", id: "fldzzJkmy9qxmRzZo", type: "date" },
      { name: "Notes", id: "fldzRAvDi6m1X30uF", type: "multilineText" },
    ],
  },
  EXECUTION_LOG: {
    tableId: "tblDNHIs9TwHGebY9",
    fields: [
      { name: "Log_Entry", id: "fldvAGyMSbF0o5ATX", type: "singleLineText" },
      { name: "Date_Time", id: "fldtWuLKDfRLqp9PQ", type: "dateTime" },
      { name: "Related_Workstream", id: "flddprXXR1Kd8KhJS", type: "multipleRecordLinks" },
      { name: "Contributor", id: "fld3IHeQHTQyYVnjE", type: "multipleRecordLinks" },
      { name: "Status", id: "fldtXlZb9M8Zed8pb", type: "singleSelect" },
      { name: "CORRECTIONS", id: "fldpmOuYVcsllvOMM", type: "multipleRecordLinks" },
      { name: "_TIER", id: "fldHZJ7oswDdR6LQM", type: "singleLineText" },
      { name: "Session_Date", id: "fld2L1mITNriwj3bU", type: "date" },
      { name: "Action_Type", id: "fldefTdTIVSwJc0BR", type: "singleSelect" },
      { name: "Tables_Affected", id: "fldw8OaKGMxLcgtBu", type: "singleLineText" },
      { name: "Summary", id: "fld3sXcFHCUyFBWP2", type: "multilineText" },
      { name: "Initiated_By", id: "fldQ2UsfIBvfnHo0d", type: "singleSelect" },
    ],
  },
  CORRECTIONS: {
    tableId: "tblSxEvYo39Pv20Ea",
    fields: [
      { name: "Correction_ID", id: "fld7YK1A4WFZSFRJt", type: "singleLineText" },
      { name: "Description", id: "fldhFv4bB26Sc8Avy", type: "multilineText" },
      { name: "Related_Execution", id: "fldAgpEfsUbipsAAI", type: "multipleRecordLinks" },
      { name: "Detected_By", id: "fldENjTD8bJjg7vx1", type: "multipleRecordLinks" },
      { name: "Date_Found", id: "fldYciwAOPudWwEUN", type: "date" },
      { name: "Resolution_Status", id: "fldIpx1uWPtypFk0W", type: "singleSelect" },
      { name: "_TIER", id: "fldMBEoU1PpdVB3Wh", type: "singleLineText" },
      { name: "Field_Corrected", id: "fldtMz5REdRVwfzNq", type: "singleLineText" },
      { name: "AI_Output", id: "fldnNMMQ0Eeb86VRP", type: "multilineText" },
      { name: "Human_Correction", id: "fldMkqw7KBDqQ8vvF", type: "multilineText" },
      { name: "Variance_Percent", id: "fldrgDeerOKv9XILG", type: "number" },
      { name: "Root_Cause", id: "fldgDPd2YvAtZylwo", type: "multilineText" },
      { name: "Corrected_By", id: "fldtPQNq766YT6dwr", type: "singleLineText" },
      { name: "Rule_Generated", id: "fldttqS321zeFEbHE", type: "checkbox" },
      { name: "Notes", id: "fldGP71ILWQvF5ASz", type: "multilineText" },
    ],
  },
  JOBS: {
    tableId: "tblgI7d8qQXY9EqJu",
    fields: [
      { name: "Job_Name", id: "fldFJZcTIP2sp5bZe", type: "singleLineText" },
      { name: "Description", id: "fldxD5Nul4nSuqY4a", type: "multilineText" },
      { name: "Workstream", id: "fldMsTrlj7UNCt4n3", type: "multipleRecordLinks" },
      { name: "Assigned_To", id: "fldmLelE6mddWCQxG", type: "multipleRecordLinks" },
      { name: "Status", id: "fldqUtK60WOiLADzB", type: "singleSelect" },
      { name: "Target_Completion", id: "fldXjmiN4gCvrKapn", type: "date" },
      { name: "Outcome", id: "fldjLdeh7j7E6ZxsZ", type: "singleLineText" },
      { name: "_TIER", id: "fldvd1BxmYncnzOBE", type: "singleLineText" },
      { name: "Date_Estimated", id: "fldEjZcM80KZiRBgt", type: "date" },
      { name: "Date_Completed", id: "fldYKYMr94UIU6mvR", type: "date" },
      { name: "Estimated_Value", id: "fldTT6SJrU00Ozsoh", type: "currency" },
      { name: "Actual_Value", id: "fld36IkSqS1oYdJGk", type: "currency" },
      { name: "Variance_Percent", id: "fld7cEZlRy3T8EOkR", type: "number" },
      { name: "Estimated_Summary", id: "fldYmXAGctpTbd4o5", type: "multilineText" },
      { name: "Actual_Summary", id: "fldcRcsGJbbN7rLKt", type: "multilineText" },
      { name: "Root_Cause_of_Variance", id: "fldLHq8Whzt16b2Sa", type: "multilineText" },
      { name: "Learning_Rule_Candidate", id: "flds8m4WdKQQbVBV0", type: "checkbox" },
    ],
  },
  HYPOTHESES: {
    tableId: "tbloQuDxUMou6XAzt",
    fields: [
      { name: "Hypothesis_Name", id: "fldDgVUhM9acf8vCH", type: "singleLineText" },
      { name: "Related_Workstream", id: "fldeVAOATViKRWWpk", type: "multipleRecordLinks" },
      { name: "Status", id: "fldvp97SDIfV4XsWx", type: "singleSelect" },
      { name: "Formulated_By", id: "fldDI7ubQt6PeV1LF", type: "multipleRecordLinks" },
      { name: "Date_Formed", id: "fldYsiF3Huy3jKfJJ", type: "date" },
      { name: "Date_Closed", id: "fld7Iej0qK9hnpu4a", type: "date" },
      { name: "Summary_of_Findings", id: "fld9iT8rBipkmgA43", type: "multilineText" },
      { name: "LEARNING_RULES", id: "fldvo1x3nUqcIxqPT", type: "multipleRecordLinks" },
      { name: "Hypothesis_Type", id: "fldEMmf9xitcstxiB", type: "singleSelect" },
      { name: "Evidence", id: "fld1k6XGhIjSxN5c8", type: "multilineText" },
      { name: "Evidence_Count", id: "fldidD5hajBvksvWA", type: "number" },
      { name: "Confidence", id: "fldMuYvz0YIpPhY4Y", type: "number" },
      { name: "Promote_to_Rule", id: "fldg1UrqXVTV4V6C3", type: "checkbox" },
      { name: "_TIER", id: "fld4546f5R5vGbYYR", type: "singleLineText" },
    ],
  },
  LEARNING_RULES: {
    tableId: "tblvuMLBiOs4qoyVv",
    fields: [
      { name: "Rule_Name", id: "fldFdGLhG2d82WrUP", type: "singleLineText" },
      { name: "Rule_Description", id: "fldMgv0wLUyiPPXfa", type: "multilineText" },
      { name: "Related_Hypothesis", id: "fldWtnBpZt7AyWAAF", type: "multipleRecordLinks" },
      { name: "Owner", id: "fldBmqdjIxv4L6fgN", type: "multipleRecordLinks" },
      { name: "Rule_Status", id: "fldg3t5exftKs5sPS", type: "singleSelect" },
      { name: "Date_Issued", id: "fldRuSXZgT1oe9qYP", type: "date" },
      { name: "Rule_Type", id: "fldngDCtTVrzkhsM9", type: "singleSelect" },
      { name: "Instance", id: "fld415EioaBGiyCAw", type: "singleLineText" },
      { name: "Trigger_Context", id: "fldbW8JZa2yqvUmAW", type: "multilineText" },
      { name: "Operational_Directive", id: "fld0lTL8CVtDrT7IL", type: "multilineText" },
      { name: "Priority", id: "fldemjP9Jx5iRU78u", type: "number" },
      { name: "Confidence_Level", id: "fldIByAyNgEu0r5QF", type: "number" },
      { name: "Override_Permission", id: "fldSkAf9L6gIUe3lo", type: "checkbox" },
      { name: "Taught_By", id: "fldFRAzhL0wy6UNwh", type: "singleLineText" },
      { name: "Applies_To", id: "fldyQFOSH3xjGCrK0", type: "singleSelect" },
      { name: "Times_Triggered", id: "fldpEdiRAnDvyAMAI", type: "number" },
      { name: "Last_Triggered", id: "fld7uH5ImT9joNv1F", type: "date" },
      { name: "Source_Correction", id: "fldVGVSpxJVA0aCfo", type: "singleLineText" },
      { name: "User_Preference_Profile", id: "fldVy33eIDVwOa6fW", type: "multilineText" },
      { name: "_TIER", id: "fldaEHp5Fn0GWiemU", type: "singleLineText" },
    ],
  },
  DOCUMENTS: {
    tableId: "tbltOoZdfc4DfPmHe",
    fields: [
      { name: "Document_Name", id: "fldKOSZ8k2Cchomgw", type: "singleLineText" },
      { name: "File", id: "fldGNRwL60fuQ4qya", type: "multipleAttachments" },
      { name: "Document_Type", id: "fldLVs6AiaQrWVNW2", type: "singleSelect" },
      { name: "Related_Workstream", id: "fldlV6N4gYBcDrvdq", type: "multipleRecordLinks" },
      { name: "Upload_Date", id: "fldAA6CYAU7cmvll8", type: "dateTime" },
      { name: "Drive_URL", id: "fld52mzQZH7ZeUxtA", type: "url" },
      { name: "Doc_Status", id: "fldaE2rxr03NbntTJ", type: "singleSelect" },
      { name: "_TIER", id: "fldWIEUK9V5ir3dNm", type: "singleLineText" },
    ],
  },
  INTELLIGENCE_SNAPSHOT: {
    tableId: "tblNzh82PswkPPMQI",
    fields: [
      { name: "Snapshot_Name", id: "fldHNRGLaTHVfZ6Hj", type: "singleLineText" },
      { name: "Description", id: "flddZZDN6LFZMz5YN", type: "multilineText" },
      { name: "Date_Created", id: "fldkMpSi0XzUqEdHZ", type: "dateTime" },
      { name: "Related_Workstream", id: "fldwulBDRTtssqFnU", type: "multipleRecordLinks" },
      { name: "Prepared_By", id: "fldif4ieEAY7Q6sKe", type: "multipleRecordLinks" },
      { name: "Snapshot_Date", id: "fldNCJckQH6UazRTp", type: "date" },
      { name: "Total_Jobs_Completed", id: "fldIslaIzIHb1bu3L", type: "number" },
      { name: "Total_Corrections", id: "fld7c8Bk6bzuCO5Q9", type: "number" },
      { name: "Total_Active_Rules", id: "fldrYrCRavlEuiDxD", type: "number" },
      { name: "Average_Variance_Percent", id: "fld7JtjOSGosisYaH", type: "number" },
      { name: "Confidence_Trajectory", id: "fld609AGG0bJ6GhK4", type: "singleSelect" },
      { name: "Known_Gaps", id: "fldpXZ730MfzhIpj3", type: "multilineText" },
      { name: "Accuracy_Summary", id: "fldvgGICdoDBe3NQM", type: "multilineText" },
      { name: "_TIER", id: "fldqH6rl7PTGhdwp9", type: "singleLineText" },
    ],
  },
} as const;

export type CoreTableName = keyof typeof CORE_SCHEMA;
