// AUTO-GENERATED from base appharWaojouHgMeW via the Airtable meta API.
// Source of truth for Core table/field IDs. Regenerate, do not hand-edit:
//   node scripts/airtable-gen-schema.mjs

export const CORE_SCHEMA = {
  ORGANISATIONS: {
    tableId: "tblhkggy89SSAjF2y",
    fields: [
      { name: "Organisation_Name", id: "fldMbFDVU01DYPnnj", type: "singleLineText" },
      { name: "Notes", id: "fldbSvrybSPNpEggA", type: "multilineText" },
      // Spec 12 (30 June 2026): free-text postal address, backported to all three
      // template bases. Additive — reads tolerate its absence on drifted bases;
      // schema-drift/migrateBaseToTemplate provisions it by name.
      { name: "Address", id: "fldOrgAddressS12x", type: "multilineText" },
      { name: "_TIER", id: "fldBdmCnujaBssKOm", type: "singleLineText" },
      { name: "Type", id: "fld7Ro0t4WVVe1wz0", type: "singleSelect" },
      { name: "Org_Status", id: "fldJrpsQRzgVOaAG5", type: "singleSelect" },
      { name: "Website", id: "fld3w41jEf6POPfmn", type: "url" },
      { name: "Industry", id: "fldP0cROxhdEOu9sa", type: "singleLineText" },
      { name: "CONTACTS", id: "fldU8Ba1i5U9fO8qc", type: "multipleRecordLinks" },
      { name: "WORKSTREAMS", id: "fld8j7wXVqDU6w6E7", type: "multipleRecordLinks" },
      { name: "PRICING", id: "fldKBBMYXQbBo31z3", type: "multipleRecordLinks" },
      { name: "TEAM", id: "fldZE6NEoQUzfi2Ul", type: "multipleRecordLinks" },
    ],
  },
  CONTACTS: {
    tableId: "tbl6xGpm3iDdMKzyB",
    fields: [
      { name: "Contact_Name", id: "fldviJRo4TY1PXCpH", type: "singleLineText" },
      { name: "First_Name", id: "fldnMUHvXq4T1aaWW", type: "singleLineText" },
      { name: "Last_Name", id: "fldPIU5fBUpspclb2", type: "singleLineText" },
      { name: "Email", id: "fldmjcyBjfsi96NYd", type: "email" },
      { name: "Phone", id: "fldVPzJEALOZm5UAK", type: "phoneNumber" },
      { name: "Organisation", id: "fldJcXYnJ4ECXJVdw", type: "multipleRecordLinks" },
      { name: "Role", id: "fldWpNiRBTTSR2kuf", type: "singleLineText" },
      { name: "LinkedIn", id: "fld8CT01YwLXn3LPk", type: "url" },
      { name: "Notes", id: "fld4mtZNWgGLAGlPG", type: "multilineText" },
      { name: "_TIER", id: "fldmE3V8ubNlcEHZd", type: "singleLineText" },
      { name: "COMMS", id: "fldlj8MQctnVBdwTC", type: "multipleRecordLinks" },
    ],
  },
  WORKSTREAMS: {
    tableId: "tbl3akARszuLzfA8M",
    fields: [
      { name: "Workstream_Name", id: "fldXO2l1fi60Djxud", type: "singleLineText" },
      { name: "Description", id: "fldraZjmwECIdAwqR", type: "multilineText" },
      { name: "Lead", id: "fldimVNEJtj2KjrN2", type: "multipleRecordLinks" },
      { name: "Status", id: "fldbgKQdSzaPjEQKk", type: "singleSelect" },
      { name: "Organisation", id: "fldcDksaDaIG4OmYw", type: "multipleRecordLinks" },
      { name: "Priority", id: "fldQHQQItXvQ1vQba", type: "singleSelect" },
      { name: "DECISIONS", id: "fld4bnSe4Kk22XMvu", type: "multipleRecordLinks" },
      { name: "EXECUTION_LOG", id: "fldAMoTbnfJcCdMmZ", type: "multipleRecordLinks" },
      { name: "JOBS", id: "fldxRFfEC5XPRND5Y", type: "multipleRecordLinks" },
      { name: "HYPOTHESES", id: "fldFmgfT90QEkwRE8", type: "multipleRecordLinks" },
      { name: "DOCUMENTS", id: "fldDXvh6oXdgC7tiW", type: "multipleRecordLinks" },
      { name: "INTELLIGENCE_SNAPSHOT", id: "fldCcBf42v2OO7U9V", type: "multipleRecordLinks" },
      { name: "_TIER", id: "fldJg1GfM9pZAzWkx", type: "singleLineText" },
      { name: "Track", id: "fldofbycTBStNsn0r", type: "singleSelect" },
      { name: "Start_Date", id: "fldV0sc2QY7HrLHMb", type: "date" },
      { name: "Target_Date", id: "fldplOKodCiTtipIh", type: "date" },
      { name: "Current_State", id: "fldA1Bka4VDigqaU4", type: "multilineText" },
      { name: "Next_Milestone", id: "fldyiGITGcZvIoNlg", type: "multilineText" },
    ],
  },
  DECISIONS: {
    tableId: "tblsHgiXa0Efo3IWD",
    fields: [
      { name: "Decision_Name", id: "fldIDXimKr7PBC41e", type: "singleLineText" },
      { name: "Decision_Description", id: "fldz30kBm8F3cyeG6", type: "multilineText" },
      { name: "Related_Workstream", id: "fldkhlCg4wEAq9Fs3", type: "multipleRecordLinks" },
      { name: "Decision_Date", id: "fldtrM1uTnlpf88Si", type: "dateTime" },
      { name: "Owner", id: "fldBnBOU8MG66EW2z", type: "multipleRecordLinks" },
      { name: "Status", id: "fldvggciokLYyx5FQ", type: "singleSelect" },
      { name: "Notes", id: "fld9Bd0Q9I4aHdhcY", type: "multilineText" },
      { name: "ISSUES", id: "fldcbxS44JV1C8ntZ", type: "multipleRecordLinks" },
      { name: "_TIER", id: "fldACe62pelNf1cjp", type: "singleLineText" },
      { name: "Decision_Type", id: "fldFyep7Zdj1TyGB5", type: "singleSelect" },
      { name: "Reversibility", id: "fldm5JcGXHe6nmn0R", type: "singleSelect" },
      { name: "Confidence", id: "fldIWCQyuCuh1SKW0", type: "number" },
      { name: "Context", id: "fldoDHCBl7JvmLZoT", type: "multilineText" },
      { name: "Decision_Made", id: "fldJvJU0acmJOI5GP", type: "multilineText" },
      { name: "Alternatives_Rejected", id: "fld6bddEWs7EQHqGp", type: "multilineText" },
      { name: "Rationale", id: "fldXH5tHvUC8RpuCi", type: "multilineText" },
      { name: "Domain", id: "fldQOD6FVY3WY2lCV", type: "singleLineText" },
      { name: "Job", id: "fldSMPaGDMcUxxUKO", type: "multipleRecordLinks" },
      { name: "COMMS", id: "flddUZaejBn5rRpso", type: "multipleRecordLinks" },
    ],
  },
  ISSUES: {
    tableId: "tblndF30LVZaHcFug",
    fields: [
      { name: "Action_Name", id: "fldNdCN0KE8ehUrHl", type: "singleLineText" },
      { name: "Description", id: "fldoGrF1qHXEVDwai", type: "multilineText" },
      { name: "Assigned_To", id: "fldZr1TGqRZ90J5jL", type: "multipleRecordLinks" },
      { name: "Due_Date", id: "fldSlWTZpxwpowc6f", type: "dateTime" },
      { name: "Status", id: "fldNrrOJDfZXb6Fzu", type: "singleSelect" },
      { name: "Linked_Decision", id: "fldZHG0j7Uv7A0xFr", type: "multipleRecordLinks" },
      { name: "Priority", id: "fldYXAZHXVK4ny8jP", type: "singleSelect" },
      { name: "_TIER", id: "fldrkJBZYILNxBq9J", type: "singleLineText" },
      { name: "Trigger_Condition", id: "fld6AKpHaHCmUIM1x", type: "multilineText" },
      { name: "Completion_Date", id: "fldzzJkmy9qxmRzZo", type: "date" },
      { name: "Notes", id: "fldzRAvDi6m1X30uF", type: "multilineText" },
      { name: "Issue_Type", id: "fldD7gM9BgnVAPF2r", type: "singleSelect" },
      { name: "CHANGE_LOG", id: "fldO5lm9AXumQdg6T", type: "multipleRecordLinks" },
      { name: "RISKS", id: "fldUhS0w8gr9sAnFp", type: "multipleRecordLinks" },
      { name: "COMMS", id: "fldOvl8lmYhl9B5vM", type: "multipleRecordLinks" },
      { name: "PROCUREMENT", id: "fldtzMThVw2Dl6yc9", type: "multipleRecordLinks" },
      { name: "TRADE_PACKAGES", id: "fldZ3meTVulqR7LYG", type: "multipleRecordLinks" },
    ],
  },
  EXECUTION_LOG: {
    tableId: "tblDNHIs9TwHGebY9",
    fields: [
      { name: "Log_Entry", id: "fldvAGyMSbF0o5ATX", type: "singleLineText" },
      { name: "Date_Time", id: "fldtWuLKDfRLqp9PQ", type: "dateTime" },
      { name: "Related_Workstream", id: "flddprXXR1Kd8KhJS", type: "multipleRecordLinks" },
      { name: "Contributor", id: "fld3IHeQHTQyYVnjE", type: "multipleRecordLinks" },
      { name: "Status", id: "fldtXlZb9M8Zed8pb", type: "singleSelect" },
      { name: "CORRECTIONS", id: "fldpmOuYVcsllvOMM", type: "multipleRecordLinks" },
      { name: "_TIER", id: "fldHZJ7oswDdR6LQM", type: "singleLineText" },
      { name: "Session_Date", id: "fld2L1mITNriwj3bU", type: "date" },
      { name: "Action_Type", id: "fldefTdTIVSwJc0BR", type: "singleSelect" },
      { name: "Tables_Affected", id: "fldw8OaKGMxLcgtBu", type: "singleLineText" },
      { name: "Summary", id: "fld3sXcFHCUyFBWP2", type: "multilineText" },
      { name: "Initiated_By", id: "fldQ2UsfIBvfnHo0d", type: "singleSelect" },
    ],
  },
  CORRECTIONS: {
    tableId: "tblSxEvYo39Pv20Ea",
    fields: [
      { name: "Correction_ID", id: "fld7YK1A4WFZSFRJt", type: "singleLineText" },
      { name: "Description", id: "fldhFv4bB26Sc8Avy", type: "multilineText" },
      { name: "Related_Execution", id: "fldAgpEfsUbipsAAI", type: "multipleRecordLinks" },
      { name: "Detected_By", id: "fldENjTD8bJjg7vx1", type: "multipleRecordLinks" },
      { name: "Date_Found", id: "fldYciwAOPudWwEUN", type: "date" },
      { name: "Resolution_Status", id: "fldIpx1uWPtypFk0W", type: "singleSelect" },
      { name: "_TIER", id: "fldMBEoU1PpdVB3Wh", type: "singleLineText" },
      { name: "Field_Corrected", id: "fldtMz5REdRVwfzNq", type: "singleLineText" },
      { name: "AI_Output", id: "fldnNMMQ0Eeb86VRP", type: "multilineText" },
      { name: "Human_Correction", id: "fldMkqw7KBDqQ8vvF", type: "multilineText" },
      { name: "Variance_Percent", id: "fldrgDeerOKv9XILG", type: "number" },
      { name: "Root_Cause", id: "fldgDPd2YvAtZylwo", type: "multilineText" },
      { name: "Corrected_By", id: "fldtPQNq766YT6dwr", type: "singleLineText" },
      { name: "Rule_Generated", id: "fldttqS321zeFEbHE", type: "checkbox" },
      { name: "Notes", id: "fldGP71ILWQvF5ASz", type: "multilineText" },
      { name: "Hypothesis", id: "fldWa0mLMiNkoRwTc", type: "multipleRecordLinks" },
    ],
  },
  JOBS: {
    tableId: "tblgI7d8qQXY9EqJu",
    fields: [
      { name: "Job_Name", id: "fldFJZcTIP2sp5bZe", type: "singleLineText" },
      { name: "Description", id: "fldxD5Nul4nSuqY4a", type: "multilineText" },
      { name: "Workstream", id: "fldMsTrlj7UNCt4n3", type: "multipleRecordLinks" },
      { name: "Assigned_To", id: "fldmLelE6mddWCQxG", type: "multipleRecordLinks" },
      { name: "Status", id: "fldqUtK60WOiLADzB", type: "singleSelect" },
      { name: "Target_Completion", id: "fldXjmiN4gCvrKapn", type: "date" },
      { name: "Outcome", id: "fldjLdeh7j7E6ZxsZ", type: "singleLineText" },
      { name: "_TIER", id: "fldvd1BxmYncnzOBE", type: "singleLineText" },
      { name: "Date_Estimated", id: "fldEjZcM80KZiRBgt", type: "date" },
      { name: "Date_Completed", id: "fldYKYMr94UIU6mvR", type: "date" },
      { name: "Estimated_Value", id: "fldTT6SJrU00Ozsoh", type: "currency" },
      { name: "Actual_Value", id: "fld36IkSqS1oYdJGk", type: "currency" },
      { name: "Variance_Percent", id: "fld7cEZlRy3T8EOkR", type: "number" },
      { name: "Estimated_Summary", id: "fldYmXAGctpTbd4o5", type: "multilineText" },
      { name: "Actual_Summary", id: "fldcRcsGJbbN7rLKt", type: "multilineText" },
      { name: "Root_Cause_of_Variance", id: "fldLHq8Whzt16b2Sa", type: "multilineText" },
      { name: "Learning_Rule_Candidate", id: "flds8m4WdKQQbVBV0", type: "checkbox" },
      { name: "RISKS", id: "fldrkbemZisTKEcMO", type: "multipleRecordLinks" },
      { name: "BUDGET", id: "fldLghkdQqY7ggDvo", type: "multipleRecordLinks" },
      { name: "CASHFLOWS", id: "fldJHQXE9ZMXovTkN", type: "multipleRecordLinks" },
      { name: "PROCUREMENT", id: "fld9FKSp5M8xd3fA8", type: "multipleRecordLinks" },
      { name: "PHASES", id: "fldOmqq7muUZEbrGK", type: "multipleRecordLinks" },
      { name: "VARIATIONS", id: "fldYyeWHIREY2NZ3K", type: "multipleRecordLinks" },
      { name: "QUOTES", id: "flds6gzxImPTKkQYD", type: "multipleRecordLinks" },
      { name: "ROOM_MATRIX", id: "fldzp9WneXhjanOiW", type: "multipleRecordLinks" },
      { name: "MEETING_MINUTES", id: "fld9ICwbbFHvZlzdA", type: "multipleRecordLinks" },
      { name: "WEEKLY_REPORTS", id: "fldJm4mQMmQtLBOIg", type: "multipleRecordLinks" },
      { name: "PHASE_EVIDENCE", id: "fldXSxJkhZgnCiUBG", type: "multipleRecordLinks" },
      { name: "BIM_MODELS", id: "fldYl7rElmrIjBirZ", type: "multipleRecordLinks" },
      { name: "ASSESSMENTS", id: "fldGrn4FL8b1BqlgL", type: "multipleRecordLinks" },
      { name: "DECISIONS", id: "fldUquk2e9tuTlbxP", type: "multipleRecordLinks" },
      { name: "COMMS", id: "fldNQW7sqmgVMzhk5", type: "multipleRecordLinks" },
    ],
  },
  HYPOTHESES: {
    tableId: "tbloQuDxUMou6XAzt",
    fields: [
      { name: "Hypothesis_Name", id: "fldDgVUhM9acf8vCH", type: "singleLineText" },
      { name: "Related_Workstream", id: "fldeVAOATViKRWWpk", type: "multipleRecordLinks" },
      { name: "Status", id: "fldvp97SDIfV4XsWx", type: "singleSelect" },
      { name: "Formulated_By", id: "fldDI7ubQt6PeV1LF", type: "multipleRecordLinks" },
      { name: "Date_Formed", id: "fldYsiF3Huy3jKfJJ", type: "date" },
      { name: "Date_Closed", id: "fld7Iej0qK9hnpu4a", type: "date" },
      { name: "Summary_of_Findings", id: "fld9iT8rBipkmgA43", type: "multilineText" },
      { name: "LEARNING_RULES", id: "fldvo1x3nUqcIxqPT", type: "multipleRecordLinks" },
      { name: "Hypothesis_Type", id: "fldEMmf9xitcstxiB", type: "singleSelect" },
      { name: "Evidence", id: "fld1k6XGhIjSxN5c8", type: "multilineText" },
      { name: "Evidence_Count", id: "fldidD5hajBvksvWA", type: "number" },
      { name: "Confidence", id: "fldMuYvz0YIpPhY4Y", type: "number" },
      { name: "Promote_to_Rule", id: "fldg1UrqXVTV4V6C3", type: "checkbox" },
      { name: "_TIER", id: "fld4546f5R5vGbYYR", type: "singleLineText" },
      { name: "Corrections", id: "fldUCa6YMQRb1nOGx", type: "multipleRecordLinks" },
    ],
  },
  LEARNING_RULES: {
    tableId: "tblvuMLBiOs4qoyVv",
    fields: [
      { name: "Rule_Name", id: "fldFdGLhG2d82WrUP", type: "singleLineText" },
      { name: "Rule_Description", id: "fldMgv0wLUyiPPXfa", type: "multilineText" },
      { name: "Related_Hypothesis", id: "fldWtnBpZt7AyWAAF", type: "multipleRecordLinks" },
      { name: "Owner", id: "fldBmqdjIxv4L6fgN", type: "multipleRecordLinks" },
      { name: "Rule_Status", id: "fldg3t5exftKs5sPS", type: "singleSelect" },
      { name: "Date_Issued", id: "fldRuSXZgT1oe9qYP", type: "date" },
      { name: "Rule_Type", id: "fldngDCtTVrzkhsM9", type: "singleSelect" },
      { name: "Instance", id: "fld415EioaBGiyCAw", type: "singleLineText" },
      { name: "Trigger_Context", id: "fldbW8JZa2yqvUmAW", type: "multilineText" },
      { name: "Operational_Directive", id: "fld0lTL8CVtDrT7IL", type: "multilineText" },
      { name: "Priority", id: "fldemjP9Jx5iRU78u", type: "number" },
      { name: "Confidence_Level", id: "fldIByAyNgEu0r5QF", type: "number" },
      { name: "Override_Permission", id: "fldSkAf9L6gIUe3lo", type: "checkbox" },
      { name: "Taught_By", id: "fldFRAzhL0wy6UNwh", type: "singleLineText" },
      { name: "Applies_To", id: "fldyQFOSH3xjGCrK0", type: "singleSelect" },
      { name: "Times_Triggered", id: "fldpEdiRAnDvyAMAI", type: "number" },
      { name: "Last_Triggered", id: "fld7uH5ImT9joNv1F", type: "date" },
      { name: "Source_Correction", id: "fldVGVSpxJVA0aCfo", type: "singleLineText" },
      { name: "User_Preference_Profile", id: "fldVy33eIDVwOa6fW", type: "multilineText" },
      { name: "_TIER", id: "fldaEHp5Fn0GWiemU", type: "singleLineText" },
    ],
  },
  DOCUMENTS: {
    tableId: "tbltOoZdfc4DfPmHe",
    fields: [
      { name: "Document_Name", id: "fldKOSZ8k2Cchomgw", type: "singleLineText" },
      { name: "File", id: "fldGNRwL60fuQ4qya", type: "multipleAttachments" },
      { name: "Document_Type", id: "fldLVs6AiaQrWVNW2", type: "singleSelect" },
      { name: "Related_Workstream", id: "fldlV6N4gYBcDrvdq", type: "multipleRecordLinks" },
      { name: "Upload_Date", id: "fldAA6CYAU7cmvll8", type: "dateTime" },
      { name: "Drive_URL", id: "fld52mzQZH7ZeUxtA", type: "url" },
      { name: "Doc_Status", id: "fldaE2rxr03NbntTJ", type: "singleSelect" },
      { name: "_TIER", id: "fldWIEUK9V5ir3dNm", type: "singleLineText" },
      { name: "PHASE_EVIDENCE", id: "fld6yg8xEhGRBOdHv", type: "multipleRecordLinks" },
    ],
  },
  INTELLIGENCE_SNAPSHOT: {
    tableId: "tblNzh82PswkPPMQI",
    fields: [
      { name: "Snapshot_Name", id: "fldHNRGLaTHVfZ6Hj", type: "singleLineText" },
      { name: "Description", id: "flddZZDN6LFZMz5YN", type: "multilineText" },
      { name: "Date_Created", id: "fldkMpSi0XzUqEdHZ", type: "dateTime" },
      { name: "Related_Workstream", id: "fldwulBDRTtssqFnU", type: "multipleRecordLinks" },
      { name: "Prepared_By", id: "fldif4ieEAY7Q6sKe", type: "multipleRecordLinks" },
      { name: "Snapshot_Date", id: "fldNCJckQH6UazRTp", type: "date" },
      { name: "Total_Jobs_Completed", id: "fldIslaIzIHb1bu3L", type: "number" },
      { name: "Total_Corrections", id: "fld7c8Bk6bzuCO5Q9", type: "number" },
      { name: "Total_Active_Rules", id: "fldrYrCRavlEuiDxD", type: "number" },
      { name: "Average_Variance_Percent", id: "fld7JtjOSGosisYaH", type: "number" },
      { name: "Confidence_Trajectory", id: "fld609AGG0bJ6GhK4", type: "singleSelect" },
      { name: "Known_Gaps", id: "fldpXZ730MfzhIpj3", type: "multilineText" },
      { name: "Accuracy_Summary", id: "fldvgGICdoDBe3NQM", type: "multilineText" },
      { name: "_TIER", id: "fldqH6rl7PTGhdwp9", type: "singleLineText" },
    ],
  },
  ASSESSMENTS: {
    tableId: "tblRMXKdV2ewscNd4",
    fields: [
      { name: "Assessment_Name", id: "fldxAxIwct0ZbozDo", type: "singleLineText" },
      { name: "Engagement_Type", id: "fldRIksgRp3Q6CaKN", type: "singleLineText" },
      { name: "Address", id: "fldCd1YzeXVUjKqlb", type: "singleLineText" },
      { name: "Suburb", id: "fldSyTBVebVr0ll7s", type: "singleLineText" },
      { name: "Size_Sqm", id: "fldQQS0EkrNKn1Nta", type: "number" },
      { name: "Scope", id: "fld6yAs2usutv16n8", type: "multilineText" },
      { name: "Result", id: "fldP8ifZ1sJ3wWFEo", type: "multilineText" },
      { name: "Status", id: "fldeGQhVOsgbIPsSg", type: "singleSelect" },
      { name: "Prompt_Version", id: "fldR0jtbOlpamDXM0", type: "singleLineText" },
      { name: "Created_By", id: "fldzMrlpEnRXMp2KN", type: "singleLineText" },
      { name: "Job", id: "fldNqAMqKvuKVLILe", type: "multipleRecordLinks" },
    ],
  },
  COMMS: {
    tableId: "tbliOGsSDXvTncEsv",
    fields: [
      { name: "Topic", id: "fld0GYzbR5UREyyD6", type: "singleLineText" },
      { name: "Message_Type", id: "fldYCy30SOn9TF2ZC", type: "singleSelect" },
      { name: "Stakeholder_Role", id: "fldfxEuFEfAf2O3hI", type: "singleSelect" },
      { name: "Due_Date", id: "fldVrUXFsUvnX8v1Q", type: "date" },
      { name: "Status", id: "fldpR6M4v9VjF6TPg", type: "singleSelect" },
      { name: "Sent_By", id: "fld5UsoDmchYu6Ghm", type: "singleLineText" },
      { name: "Notes", id: "fldTQNR1UreSjAGUa", type: "multilineText" },
      { name: "Job", id: "fldSaLSpKfbSYTEZT", type: "multipleRecordLinks" },
      { name: "Stakeholder", id: "fldZS4i8gA1DWyING", type: "multipleRecordLinks" },
      { name: "Phase", id: "fld6Rr0sZD9YtBmYa", type: "multipleRecordLinks" },
      { name: "Linked_Issue", id: "fld24l8HS9ZINTg9y", type: "multipleRecordLinks" },
      { name: "Linked_Decision", id: "fldetrxR3Uj9cmfA9", type: "multipleRecordLinks" },
    ],
  },
  PENDING_WRITES: {
    tableId: "tblyZy4rGXGFdJcqo",
    fields: [
      { name: "Table_Key", id: "fldZBlEgZJEm1ZAuR", type: "singleLineText" },
      { name: "Op", id: "fldklvLAgUP1Pdxp0", type: "singleSelect" },
      { name: "Record_Id", id: "fldADJXijnvq9qkzy", type: "singleLineText" },
      { name: "Payload", id: "fldqkHUWBxoi247sP", type: "multilineText" },
      { name: "Actor_Type", id: "fld0ROFgNIomrE1Iy", type: "singleLineText" },
      { name: "Actor_Name", id: "fldr6adfk3zcNlnfl", type: "singleLineText" },
      { name: "Status", id: "fldohpb5RTYrGV7iX", type: "singleSelect" },
      { name: "Created_At", id: "fldGEnUMauXsuD87c", type: "dateTime" },
      { name: "Expires_At", id: "fldt1jGjOQsNTXK0f", type: "dateTime" },
      { name: "Job_Id", id: "fldbvw8n45YLyT3Yt", type: "singleLineText" },
      { name: "Resolved_By", id: "fldZllSrKYXPgWkoA", type: "singleLineText" },
      { name: "Resolved_At", id: "fldvfmZBWwaxeWCY3", type: "dateTime" },
      { name: "Error", id: "fldfdDJP5eeXBl4vt", type: "multilineText" },
    ],
  },
  CHAT_SESSIONS: {
    tableId: "tblzkkG3sN8tERVOA",
    fields: [
      { name: "Session_Title", id: "fldy81hXkXzyfxuj4", type: "singleLineText" },
      { name: "Job_Id", id: "fldSAsKtteNMBj1pv", type: "singleLineText" },
      { name: "Started_At", id: "fldhJy0ARI9r8oQz0", type: "dateTime" },
      { name: "Ended_At", id: "fldy8Zu8Z79Np0OkJ", type: "dateTime" },
      { name: "Summary", id: "fldX8rWR9JdEfeidq", type: "multilineText" },
    ],
  },
  CHAT_MESSAGES: {
    tableId: "tblyee39q6kjw90q7",
    fields: [
      { name: "Session_Id", id: "fldhEWkCmVzpsaGmi", type: "singleLineText" },
      { name: "Role", id: "fldP72VWAvEFYlReU", type: "singleLineText" },
      { name: "Content", id: "fldJwNv5jzARQIfU8", type: "multilineText" },
      { name: "Tool_Calls", id: "fldw5Vw22iaXHds6r", type: "multilineText" },
      { name: "Created_At", id: "fldC5t5Tdy2DbpcqF", type: "dateTime" },
    ],
  },
  RISKS: {
    tableId: "tblEbI90SA3szwngA",
    fields: [
      { name: "Risk", id: "fldQzpdBAxcjO1O3m", type: "singleLineText" },
      { name: "Likelihood", id: "fldnGGZyZYgEx5mWL", type: "number" },
      { name: "Impact", id: "fldYy1gwsdZ1Ahoo0", type: "number" },
      { name: "Mitigation", id: "fldbUoTabBTtw9TLG", type: "multilineText" },
      { name: "Status", id: "fldD6l7179qGUfHeL", type: "singleSelect" },
      { name: "Owner", id: "fldvOAP0kBslgIYJH", type: "singleLineText" },
      { name: "Escalated_At", id: "fldF1uRsHNySIw9X0", type: "date" },
      { name: "Escalation_Note", id: "fldSIll1oQalMaTcE", type: "multilineText" },
      { name: "Created_By_AI", id: "fldjjYDJ55T72iKEo", type: "checkbox" },
      { name: "Job", id: "fldLPvL4InYpnodoF", type: "multipleRecordLinks" },
      { name: "Linked_Issues", id: "fldIivhyzWlYK1r9s", type: "multipleRecordLinks" },
      // Spec 12 Module 5 RISKS fields. Additive — reads tolerate absence on
      // drifted bases; schema-drift/migrateBaseToTemplate provisions them by
      // name. Not yet written by the app (bases must carry the fields first).
      { name: "Category", id: "fldRiskCategoryS12", type: "singleSelect" },
      { name: "RAG", id: "fldRiskRAGS12x", type: "singleSelect" },
      { name: "Phase", id: "fldRiskPhaseS12x", type: "multipleRecordLinks" },
    ],
  },
  VENDORS: {
    tableId: "tblPUukY1qe9grieM",
    fields: [
      { name: "Vendor_Name", id: "fldEgBZCi3TM1rN9O", type: "singleLineText" },
      { name: "Category", id: "fldY14QOr0WDbxSoe", type: "singleLineText" },
      { name: "Contact_Name", id: "fld9r3FbFcjsuUeCj", type: "singleLineText" },
      { name: "Contact_Email", id: "fldUw1DveDvyF6Egy", type: "singleLineText" },
      { name: "Contact_Phone", id: "fldilqDudw2ojhclz", type: "singleLineText" },
      { name: "Rating", id: "fldxw9caJ0WFJsMJ9", type: "number" },
      { name: "Notes", id: "fldJCtTMZOmbLGMeT", type: "multilineText" },
      { name: "Is_Active", id: "fldKtiq1Mg56lMmZy", type: "checkbox" },
    ],
  },
  BUDGET: {
    tableId: "tblXhCWTyRKJ6zFFG",
    fields: [
      { name: "Budget_Category", id: "fldfqjLj1h3gGF2MO", type: "singleLineText" },
      { name: "Estimated", id: "fldY1Y4BSev6BGDtf", type: "currency" },
      { name: "Actual", id: "fld9Udt8mezHFvex3", type: "rollup" },
      { name: "Forecast", id: "fldwIhVpxQJlgd31e", type: "currency" },
      { name: "Variance", id: "fldGFBC9j4ZUOmVI0", type: "currency" },
      { name: "RAG", id: "fldzk3PLruhilpPkv", type: "singleSelect" },
      { name: "Phase", id: "fldbrEpnCsK4eLQHQ", type: "multipleRecordLinks" },
      { name: "Job", id: "fldMwQVYws4IZGgAM", type: "multipleRecordLinks" },
      { name: "Notes", id: "fldpsvl04BPmZJDXB", type: "multilineText" },
      { name: "_TIER", id: "fldaSO1qM5m8otHWv", type: "singleLineText" },
      { name: "PROCUREMENT", id: "fldHiEeVVWRtVkh9x", type: "multipleRecordLinks" },
    ],
  },
  CASHFLOWS: {
    tableId: "tbl5R74PIPjaw8yLp",
    fields: [
      { name: "Cashflow_Name", id: "fld7Sc3TMwrs2HOcP", type: "singleLineText" },
      { name: "Period", id: "fldYmfYMLzq2CNefC", type: "singleLineText" },
      { name: "Type", id: "fldu2E7Z3Ew3kWrTJ", type: "singleSelect" },
      { name: "Amount", id: "fldagoIfcj0uiORRl", type: "currency" },
      { name: "Source_Or_Payee", id: "fld0t1PHYMaTFOME6", type: "singleLineText" },
      { name: "Category", id: "fldpsN2WNZaCI3Mm5", type: "singleLineText" },
      { name: "Status", id: "fldGE1rTvGkgtWAM6", type: "singleSelect" },
      { name: "Job", id: "fldSgUEra1pve5uw6", type: "multipleRecordLinks" },
      { name: "Notes", id: "fldLYeGy9PYRLLr9u", type: "multilineText" },
      { name: "_TIER", id: "fldWqmm8NARcGPmav", type: "singleLineText" },
    ],
  },
  PLAN: {
    tableId: "tbleJO6vMg9PrAFOS",
    fields: [
      { name: "Task_Name", id: "fldxtpPFT8Ibe8OMt", type: "singleLineText" },
      { name: "Phase", id: "fldHTsJv7L5aa43S3", type: "multipleRecordLinks" },
      { name: "Job", id: "fldYxvZJ1cRbVBgWi", type: "multipleRecordLinks" },
      { name: "Start_Date", id: "fldkByTXq6w4yXo12", type: "date" },
      { name: "End_Date", id: "fldnWjsWJzIiJlYjP", type: "date" },
      { name: "Duration_Days", id: "fldMpt7lREgV4Fl8d", type: "number" },
      { name: "Assigned_To", id: "fldXoulT2depz3byi", type: "multipleRecordLinks" },
      { name: "Status", id: "fld8Wsm8MDOBnj7ZJ", type: "singleSelect" },
      { name: "RAG", id: "fld1nIjpAoHMZxRhI", type: "singleSelect" },
      { name: "Notes", id: "fldoRLM3AU6vIEwva", type: "multilineText" },
      { name: "_TIER", id: "fldIAJRxjg1eJGpzG", type: "singleLineText" },
      { name: "PROCUREMENT", id: "fld0iMqNrTtbYwC9p", type: "multipleRecordLinks" },
      { name: "Predecessor", id: "fldg6KLMNm6DoXuwa", type: "multipleRecordLinks" },
      { name: "Successor_Tasks", id: "flddyyX9UPgBJf2uB", type: "multipleRecordLinks" },
      { name: "QUANTITY_TAKEOFF", id: "flddwvtAFSOwQxo2H", type: "multipleRecordLinks" },
    ],
  },
  CHANGE_LOG: {
    tableId: "tblHz2p7IytBBxOSx",
    fields: [
      { name: "Change_Name", id: "fld9jGoBtYPH48V3n", type: "singleLineText" },
      { name: "Change_Type", id: "fldFnwaaNlqg15TXU", type: "singleSelect" },
      { name: "Description", id: "fldt3WGG3Kel2ijWv", type: "multilineText" },
      { name: "Status", id: "fldLkjoWaoMSCKJXg", type: "singleSelect" },
      { name: "Impact_Cost", id: "fldKmoHuG3btCzDc3", type: "currency" },
      { name: "Impact_Schedule_Days", id: "fldbwe17BtiPKhiJI", type: "number" },
      { name: "Date_Raised", id: "fldZkuaA4oGZlvHzi", type: "date" },
      { name: "Date_Resolved", id: "fldEyi0YW05NMJ5zU", type: "date" },
      { name: "Raised_By", id: "fldwYlHuzo6EVrNPT", type: "singleLineText" },
      { name: "Job", id: "fldJ2fiOWZVMV3Y67", type: "multipleRecordLinks" },
      { name: "Phase", id: "flduxqzA2fufQ7js2", type: "multipleRecordLinks" },
      { name: "Linked_Issue", id: "fldhq6IVZzEH2rUv2", type: "multipleRecordLinks" },
      { name: "Notes", id: "fldNncQ7CSXr2LLUa", type: "multilineText" },
      { name: "_TIER", id: "fldh14HZztCGE68k9", type: "singleLineText" },
    ],
  },
  REGIONS: {
    tableId: "tblsS1MmXNpO0KfcX",
    fields: [
      { name: "Region_Name", id: "fldhGzbGGC6oQowVz", type: "singleLineText" },
      { name: "Region_Code", id: "fldCnCQCoStxWjAdb", type: "singleLineText" },
      { name: "Parent_Region", id: "fldsJBJySGszCVOsN", type: "singleLineText" },
      { name: "Notes", id: "flddGsI7pXYaw8NjY", type: "multilineText" },
      { name: "Travel_Days", id: "fldprt5DuBf2MR5hD", type: "number" },
      { name: "Travel_Rate_Per_Day", id: "fldxEI9PyHJGKJs19", type: "currency" },
      { name: "Postcodes", id: "fld2spaCeMAbNcvg5", type: "multilineText" },
      { name: "Regional_Notes", id: "fldtVOiahDPryIBeT", type: "multilineText" },
      { name: "Active", id: "fld4M1nUMXxe4vkc7", type: "checkbox" },
      { name: "_TIER", id: "fldaTEzXjScUcZnsX", type: "singleLineText" },
    ],
  },
  DOMAIN_LABELS: {
    tableId: "tbly2PvkPBMX1kcQS",
    fields: [
      { name: "Label_ID", id: "fldqwrwBmEHkqptBD", type: "singleLineText" },
      { name: "Core_Field_Label", id: "fldNIUgb5WNFP15dt", type: "singleLineText" },
      { name: "Core_Table", id: "fldQjIqYtwoKJCLLU", type: "singleSelect" },
      { name: "Domain_Label", id: "fldrQ0ZppKA0cUmdv", type: "multilineText" },
      { name: "Active", id: "fldV8noD99bJPqOKl", type: "checkbox" },
      { name: "_TIER", id: "fldLITs1H1jdvwrCm", type: "singleLineText" },
      { name: "Domain", id: "fldWcqWh1WfxjNvPR", type: "singleSelect" },
      { name: "Context_Note", id: "fldDoqADkcagriLqK", type: "multilineText" },
    ],
  },
  ENGAGEMENT_TYPE_CONFIG: {
    tableId: "tblucBglOFGc7SGsU",
    fields: [
      { name: "Config_Name", id: "flddUFFeswlfSKvzI", type: "singleLineText" },
      { name: "Engagement_Type", id: "fldIqMkkTK97rdY8J", type: "singleSelect" },
      { name: "Active", id: "fldhK6GvtYscJ5XCN", type: "checkbox" },
      { name: "Phase_Template", id: "fldSPVUU7EiDeAjSh", type: "multilineText" },
      { name: "Plan_View", id: "flddyEMKTNlGUOQeh", type: "singleSelect" },
      { name: "Full_Risk_Register", id: "fldoCSt8kiFYjfbLx", type: "checkbox" },
      { name: "Cashflow_Period", id: "fld3s0efcxK04wnXp", type: "singleLineText" },
      { name: "Notes", id: "fld9oRsGlIoPjduGS", type: "multilineText" },
      { name: "_TIER", id: "fld81I5WHUerf6wlg", type: "singleLineText" },
    ],
  },
  PROCUREMENT: {
    tableId: "tbl0TPWCj72lDGpPM",
    fields: [
      { name: "Procurement_Name", id: "fld7pofDPc4HZI98T", type: "singleLineText" },
      { name: "Job", id: "fldYqVdTHYyHQXAmd", type: "multipleRecordLinks" },
      { name: "Phase", id: "fldsI8a05scY2wkYL", type: "multipleRecordLinks" },
      { name: "Plan_Task", id: "fld4YfGD3UYofPSRi", type: "multipleRecordLinks" },
      { name: "Supplier", id: "fld3PKrrz8XWENE2N", type: "multipleRecordLinks" },
      { name: "Quantity", id: "fldbS6bhTddP7bZDy", type: "number" },
      { name: "Unit", id: "fldwxeqBYQVQj59qy", type: "singleLineText" },
      { name: "Unit_Cost", id: "fldgpRIZUQoRwQc5K", type: "currency" },
      { name: "Budget_Category", id: "fld7BNvdvaDlif9rK", type: "multipleRecordLinks" },
      { name: "Order_Date", id: "fldEMUOM6JUNByN8l", type: "date" },
      { name: "Expected_Date", id: "fldimi57tID6J1I4b", type: "date" },
      { name: "Actual_Date", id: "fldgVuccb1jAitOAE", type: "date" },
      { name: "Status", id: "fldSU9nRTEPQYXLbu", type: "singleSelect" },
      { name: "Invoice_Reference", id: "fldOpBe2k0aM354iV", type: "singleLineText" },
      { name: "Linked_Issue", id: "fldIHVrm3GWwb164C", type: "multipleRecordLinks" },
      { name: "Notes", id: "fldBdddRzSBKvgop4", type: "multilineText" },
      { name: "_TIER", id: "fld7FJwoTnKKuLo8f", type: "singleLineText" },
      { name: "Total_Cost", id: "fldXHv0TYGO2goobL", type: "formula" },
      { name: "CONTRACTOR_BIDS", id: "fldaUz31VIr3F6YkO", type: "multipleRecordLinks" },
    ],
  },
  PHASES: {
    tableId: "tblFxEPfiSEfC2zXY",
    fields: [
      { name: "Phase_Name", id: "fld7dyHls35ca4VRr", type: "singleLineText" },
      { name: "Status", id: "fldWMknKbZ2RiA2xJ", type: "singleSelect" },
      { name: "Completion_Pct", id: "fldLKJk68M4d68pRN", type: "number" },
      { name: "Sort_Order", id: "fld6JD7cRL3eatUan", type: "number" },
      { name: "Start_Date", id: "fldYnqJVf7x2cgFUd", type: "date" },
      { name: "End_Date", id: "fldtIWDt5tpJZZhvh", type: "date" },
      { name: "Is_AI_Draft", id: "fldOB4ccqicPX3Vyp", type: "checkbox" },
      { name: "Approved_By", id: "fldCiwGu3SDRoWHbM", type: "singleLineText" },
      { name: "Job", id: "fldxxtPokdLt8rTGO", type: "multipleRecordLinks" },
      { name: "PHASE_EVIDENCE", id: "fldN9ynSVBzWUeOjL", type: "multipleRecordLinks" },
      { name: "COMMS", id: "fldyVOn7q6m4y2Ela", type: "multipleRecordLinks" },
      { name: "Phase_Type", id: "fldfDgSTR3XqJdBO1", type: "singleSelect" },
      { name: "Loop_Permitted", id: "fldW7GRnTykr1NdfD", type: "checkbox" },
      { name: "RAG", id: "fldSiAbSDh9NQBJkG", type: "singleSelect" },
      { name: "Sequence", id: "fldws3MNEonDYLwTT", type: "number" },
      { name: "Season_Year", id: "fldKbljacRpxyb34M", type: "singleLineText" },
      { name: "Predecessor_Phase", id: "fldR43yBMtauVbeu6", type: "multipleRecordLinks" },
      { name: "Successor_Phases", id: "fldMJUi4SkCIsj75N", type: "multipleRecordLinks" },
      { name: "ISSUES", id: "fldhAWJMTBXSXXuyB", type: "multipleRecordLinks" },
    ],
  },
  VARIATIONS: {
    tableId: "tbl8IMGCLofaXuxKK",
    fields: [
      { name: "Title", id: "fld2uLTokYbsZi90E", type: "singleLineText" },
      { name: "Ref_Number", id: "fld4XT4XOQxpqbgBa", type: "singleLineText" },
      { name: "Description", id: "fldp8ucpKNKfGadLq", type: "multilineText" },
      { name: "Scope_Change", id: "fldCJs6Wf7JauOwi5", type: "multilineText" },
      { name: "Cost_Impact", id: "fldBdZCj3cgl5FAsn", type: "currency" },
      { name: "Time_Impact_Days", id: "fldWv3tnhZc3rgiqG", type: "number" },
      { name: "Status", id: "fldB6dXjIOJgy0sNO", type: "singleSelect" },
      { name: "Submitted_By", id: "fldOyURjzToxvVmyJ", type: "singleLineText" },
      { name: "Approved_By", id: "fldmyBHXG3bAiBQuN", type: "singleLineText" },
      { name: "Approved_At", id: "fldvVvHa5nI6nR83m", type: "date" },
      { name: "Job", id: "fldT4F1ccfLCSA3ZJ", type: "multipleRecordLinks" },
      { name: "Is_AI_Drafted", id: "fldhRJefKfUcc22U5", type: "checkbox" },
      { name: "AI_Draft", id: "fldDIXN9W2xBiBc7H", type: "multilineText" },
    ],
  },
  QUOTES: {
    tableId: "tblFbD2qTNHQFsL60",
    fields: [
      { name: "Title", id: "fldENrr6wp8uK0MbL", type: "singleLineText" },
      { name: "Ref_Number", id: "fldTSKiqfzEaBUstb", type: "singleLineText" },
      { name: "Client_Name", id: "flddmcYlK3Orbp6qh", type: "singleLineText" },
      { name: "Status", id: "fldkRBh8WR1K3sg3W", type: "singleSelect" },
      { name: "GST_Rate", id: "fldzZaeXu1o4zO6OY", type: "number" },
      { name: "Subtotal", id: "fldwX0yyycE7NgRbJ", type: "currency" },
      { name: "GST_Amount", id: "fld1Esk1tZ8jg2jDx", type: "currency" },
      { name: "Total", id: "fldqYM6y1lUVe6uRq", type: "currency" },
      { name: "Notes", id: "fldcym3Li0ehgiTbj", type: "multilineText" },
      { name: "Valid_Until", id: "fldncJqpidzEESZgY", type: "date" },
      { name: "Job", id: "fldirLxrGLxK38ZsW", type: "multipleRecordLinks" },
      { name: "QUOTE_LINES", id: "fldvI7Sb4nUkScdjS", type: "multipleRecordLinks" },
    ],
  },
  QUOTE_LINES: {
    tableId: "tbldMARQliqJzPs6a",
    fields: [
      { name: "Description", id: "fldc0rmOwjjNAokGc", type: "singleLineText" },
      { name: "Category", id: "fldMR6VAS7KMXxJQ8", type: "singleLineText" },
      { name: "Qty", id: "fldTHBNAJGArK2MdZ", type: "number" },
      { name: "Unit", id: "fld4fx8lxKxVHgkic", type: "singleLineText" },
      { name: "Unit_Price", id: "fldIzuofwVj4xC1Zt", type: "currency" },
      { name: "Line_Total", id: "fldS9tu3wzPvNYdFi", type: "currency" },
      { name: "Sort_Order", id: "fldg4GewyhJkOkDFC", type: "number" },
      { name: "Quote", id: "fldqTe8hnQWbW5g5k", type: "multipleRecordLinks" },
    ],
  },
  ROOM_MATRIX: {
    tableId: "tblmFdptBnSfAsJmi",
    fields: [
      { name: "Room_Name", id: "fldvHT52WO2c1uMKU", type: "singleLineText" },
      { name: "Zone", id: "fldjxvmDTeYpynjRG", type: "singleLineText" },
      { name: "Area_Sqm", id: "fldIFt9ofBMwoJDNG", type: "number" },
      { name: "Ceiling_Height", id: "fldY4oSqivpSXeQJv", type: "singleLineText" },
      { name: "Notes", id: "fldYStTGFh2HqWKmB", type: "multilineText" },
      { name: "Job", id: "fldjnCF336JMUbq9E", type: "multipleRecordLinks" },
      { name: "Finishes", id: "fldOz4uQZz9cGxxJH", type: "multilineText" },
    ],
  },
  MEETING_MINUTES: {
    tableId: "tbloO1G0aruLMmD20",
    fields: [
      { name: "Title", id: "fldw2xol9gnzNNsNH", type: "singleLineText" },
      { name: "Meeting_Date", id: "fldaoCp3oxId23oPe", type: "date" },
      { name: "Attendees", id: "fldEJ26LUFojQtpmU", type: "singleLineText" },
      { name: "Raw_Minutes", id: "fld7FeeUEY5k95YYW", type: "multilineText" },
      { name: "Actions_Count", id: "fldbxfItFthrXqJx8", type: "number" },
      { name: "Status", id: "fldocbbXttasqYNQ1", type: "singleSelect" },
      { name: "Job", id: "fldzZBGSUm6Dzvqh2", type: "multipleRecordLinks" },
      { name: "Extracted_Actions", id: "fldVp1K4sPrMxKLqd", type: "multilineText" },
      { name: "Confirmed_At", id: "fldywSZI9hbseY6cd", type: "date" },
    ],
  },
  WEEKLY_REPORTS: {
    tableId: "tblAB2ccbhD170xnp",
    fields: [
      { name: "Title", id: "fldGTMO7R7ngJsY49", type: "singleLineText" },
      { name: "Week_Ending", id: "fldWzu4H3YfKEOH9Y", type: "date" },
      { name: "Content", id: "fldUPTGFeJwnHRDNb", type: "multilineText" },
      { name: "Is_AI_Generated", id: "fldgRdsP3GQWqf3Un", type: "checkbox" },
      { name: "Status", id: "fld5gkDPwvTu8tayW", type: "singleSelect" },
      { name: "Approved_By", id: "fldIpsEIeRlU6YVGS", type: "singleLineText" },
      { name: "Job", id: "fldj9rqT82gkaZAUg", type: "multipleRecordLinks" },
      { name: "Generated_At", id: "fldqjxkDvZ0Tlk0DT", type: "date" },
      { name: "Approved_At", id: "fldANCOuF7k4uuwhI", type: "date" },
      { name: "Sent_At", id: "flduG4B5SQvwptT4Z", type: "date" },
    ],
  },
  PHASE_EVIDENCE: {
    tableId: "tbl1s1LERe6a4jSCq",
    fields: [
      { name: "Note", id: "flddrLgM4UovnxiBQ", type: "singleLineText" },
      { name: "Added_By", id: "fldINPg4SWuY8knr7", type: "singleLineText" },
      { name: "Phase", id: "fldzicNdWJoRRpIwv", type: "multipleRecordLinks" },
      { name: "Document", id: "fldb6DZZtlE2AbFTA", type: "multipleRecordLinks" },
      { name: "Job", id: "fldaKth0ZqC2AS6xZ", type: "multipleRecordLinks" },
    ],
  },
  BIM_MODELS: {
    tableId: "tblKseu6UAqq04MvC",
    fields: [
      { name: "Name", id: "fld0Dt7Ry1QsOuXRN", type: "singleLineText" },
      { name: "Provider", id: "fldEiJCwakZBHCjyf", type: "singleLineText" },
      { name: "Embed_URL", id: "fldEIxAoqdSwf4d7e", type: "url" },
      { name: "Client_Visible", id: "fldOcRhpWHR9wtufV", type: "checkbox" },
      { name: "Added_By", id: "fldUsbDfhKU8bXjIw", type: "singleLineText" },
      { name: "Notes", id: "fld63IKXnKOyE9VcC", type: "multilineText" },
      { name: "Job", id: "fldXrxZggqvJuXLLk", type: "multipleRecordLinks" },
    ],
  },
  PLAT_CFG_REFERENCE: {
    tableId: "tblRu1DohdoP2Ej1v",
    fields: [
      { name: "Name", id: "fld2PAHPnxJQPfp6P", type: "singleLineText" },
      { name: "Ref_Type", id: "fld5OMMFeL1ASHnir", type: "singleLineText" },
      { name: "Code", id: "fldhwuIV0mMW4rlyU", type: "singleLineText" },
      { name: "Value", id: "fldKxmXM4AzO37bE1", type: "multilineText" },
      { name: "Sort_Order", id: "fldy2kbNnF5wyTCOd", type: "number" },
      { name: "Is_Active", id: "fldiPRCHM7Ftgn05w", type: "checkbox" },
    ],
  },
  PLAT_CFG_REGION: {
    tableId: "tblSaqFt8AX3DknV4",
    fields: [
      { name: "Region_Name", id: "fldeJ3spoP6qW9I6h", type: "singleLineText" },
      { name: "Postcodes", id: "fldx2ZhZLwDFghVUv", type: "multilineText" },
      { name: "Travel_Days", id: "fldGkgYUqvhaLJOMo", type: "number" },
      { name: "Premium_Pct", id: "fldgX39bsq9xlBfya", type: "number" },
      { name: "Is_Active", id: "fldJy3AhWyqfFoXVh", type: "checkbox" },
    ],
  },
  PLAT_CFG_NOMENCLATURE: {
    tableId: "tblvRv6aNjTE8MzLU",
    fields: [
      { name: "Customer_Term", id: "fldBnoDFOzvOEBRYv", type: "singleLineText" },
      { name: "Standard_Term", id: "fldNXUCKl3HJsIjB5", type: "singleLineText" },
    ],
  },
  PLAT_CFG_SETTING: {
    tableId: "tbl9NfLkhS8DICctV",
    fields: [
      { name: "Setting_Key", id: "fld3tEBOgc2NzdLfI", type: "singleLineText" },
      { name: "Value", id: "fldD7K9g50w7X9bFH", type: "multilineText" },
    ],
  },
  ROOFING_CONTACTS: {
    tableId: "tbl9INNDYYPON38Jr",
    fields: [
      { name: "Contact_Name", id: "fldA0PLRd1opoJXq6", type: "singleLineText" },
      { name: "Email", id: "fldYByNcK9d9rd09I", type: "email" },
      { name: "Phone", id: "fldhWF4Y0tw4YUUl7", type: "phoneNumber" },
      { name: "Company", id: "fldV5McSfd6XcI7M1", type: "singleLineText" },
      { name: "Address", id: "fldWEKV5ovxh0ZxRX", type: "multilineText" },
    ],
  },
  ROOFING_RATE_CARDS: {
    tableId: "tbl1wDseQODNjmlG9",
    fields: [
      { name: "Material", id: "fld1ptpgyv4qW3urG", type: "singleLineText" },
      { name: "Pitch_Type", id: "fldhvZLgSrlc764MA", type: "singleLineText" },
      { name: "Description", id: "fldrb71Zyo5yr16hf", type: "multilineText" },
      { name: "Unit", id: "fldEXL6wghZVACDXn", type: "singleLineText" },
      { name: "Rate_Ex_GST", id: "fldpdEf2dfmgcPWSL", type: "currency" },
      { name: "Is_Active", id: "fldJH2JOw5hSNl6au", type: "checkbox" },
    ],
  },
  ROOFING_FINANCE_PROVIDERS: {
    tableId: "tblsFAjoezpt1oCj5",
    fields: [
      { name: "Name", id: "fldZpiSviGXoO9gRD", type: "singleLineText" },
      { name: "Interest_Rate_Pct", id: "fldGKNRU7B5CBwV8d", type: "number" },
      { name: "Min_Term_Months", id: "fldvC3EZKLpOw1G6V", type: "number" },
      { name: "Max_Term_Months", id: "fldzbfiROhEfmTqgR", type: "number" },
      { name: "Tagline", id: "fldQUhyfzBcILnDZm", type: "singleLineText" },
      { name: "Is_Active", id: "fld3KJhEpvM5AarTk", type: "checkbox" },
    ],
  },
  ROOFING_GUTTERING_RATES: {
    tableId: "tblYoH8DE3ssZ2UGU",
    fields: [
      { name: "Item_Type", id: "fldoAEP2far7v4LKC", type: "singleLineText" },
      { name: "Description", id: "flddZtPvwWdrRzY80", type: "singleLineText" },
      { name: "Rate_Ex_GST", id: "flduHpb8peiU2eabG", type: "currency" },
      { name: "Unit", id: "fldHw8IVbmMvlEfOt", type: "singleLineText" },
      { name: "Is_Active", id: "fldLZRnzueU6Bcm4W", type: "checkbox" },
    ],
  },
  ROOFING_REGIONS: {
    tableId: "tblFQ52z6Do1BcUAy",
    fields: [
      { name: "Name", id: "fld5nM4q4rPnH5UIU", type: "singleLineText" },
      { name: "Postcodes", id: "fldNX18UpYXvlOuw9", type: "singleLineText" },
      { name: "Travel_Days", id: "fldCzsfWvSlACu9xP", type: "number" },
      { name: "Travel_Rate", id: "fldxa6daI3sEOn9iH", type: "currency" },
      { name: "Premium_Pct", id: "fldedUljw2ylfZZlV", type: "number" },
      { name: "Is_Active", id: "fldYulKQT9BErzaxt", type: "checkbox" },
    ],
  },
  ROOFING_TEAM: {
    tableId: "tblD8jJYxonsPx7MP",
    fields: [
      { name: "Name", id: "fldQ8qKXHKc2ybHhl", type: "singleLineText" },
      { name: "Role", id: "fldYGcnA0aC6MfsBt", type: "singleSelect" },
      { name: "Accuracy_Profile", id: "fldHm524hjoxEyMWB", type: "singleLineText" },
      { name: "Date_Joined", id: "fldO3tSKwLD2zOCD4", type: "date" },
      { name: "Is_Active", id: "fldy6JkPUs667jHCC", type: "checkbox" },
    ],
  },
  ROOFING_SOLAR_PARTNERS: {
    tableId: "tblynX9gI5XfLUAWE",
    fields: [
      { name: "Name", id: "fldaKOfPXp3wWmqdA", type: "singleLineText" },
      { name: "Contact_Name", id: "fldVD3n03rTHH2lHZ", type: "singleLineText" },
      { name: "Contact_Email", id: "fldnMpOSRlJ9nlrIk", type: "email" },
      { name: "Referral_Fee_Pct", id: "fld3dsEAdcGTZcnXy", type: "number" },
      { name: "Avg_Install_Value", id: "fldVQ4a1mX78olGjK", type: "currency" },
      { name: "Is_Active", id: "fldPSo1RdB1BUs3rz", type: "checkbox" },
    ],
  },
  ROOFING_WORKSTREAMS: {
    tableId: "tblIE4zWIICgeMETX",
    fields: [
      { name: "Name", id: "fldeqSVHZmI7Pw1My", type: "singleLineText" },
      { name: "Description", id: "fld79yKilumKMWicH", type: "multilineText" },
      { name: "Milestone", id: "fld5K5NqipBZphPkB", type: "singleLineText" },
      { name: "Status", id: "fldRSjPiS9aaBYngz", type: "singleSelect" },
      { name: "Load_At_Session_Start", id: "fldZUHosVLaWchp8P", type: "checkbox" },
      { name: "Notes", id: "fldrO2Hi2G9ytAhLX", type: "multilineText" },
      { name: "Last_Updated", id: "fldw3QfcZdhJfgqXn", type: "date" },
    ],
  },
  ROOFING_PRICE_CHECK_LOG: {
    tableId: "tblicf2SVBJQzRrIG",
    fields: [
      { name: "Summary", id: "fld4skbzdQh5dkYNM", type: "singleLineText" },
      { name: "Run_At", id: "fldQwotro9BP7nFjB", type: "dateTime" },
      { name: "Status", id: "fldY33uGw2gmi4ZSc", type: "singleLineText" },
      { name: "Vendors_Checked", id: "fldumTQ9ap2WOTKH6", type: "number" },
      { name: "Prices_Updated", id: "fldur9KjdgL2nrgs4", type: "number" },
      { name: "Prices_Unchanged", id: "fldBtugJByzRsxgYC", type: "number" },
      { name: "Errors", id: "fldn50BQBjhZGynr1", type: "number" },
    ],
  },
  ROOFING_ACTION_HUB: {
    tableId: "tblEA6u7XpSdVBGJ0",
    fields: [
      { name: "Action", id: "fldkIdF1fwiuc1y2T", type: "singleLineText" },
      { name: "Priority", id: "fldEGhOXWanzeuisu", type: "singleSelect" },
      { name: "Due_Date", id: "fldZIifHA2DmbdeKT", type: "date" },
      { name: "Trigger_Condition", id: "fldhq7Ho4EvtFJnJC", type: "singleLineText" },
      { name: "Status", id: "fld7EK94T2DlFiSyX", type: "singleSelect" },
      { name: "Notes", id: "fldYXX4lB7mxcyxTQ", type: "multilineText" },
    ],
  },
  ROOFING_EXECUTION_LOG: {
    tableId: "tbl3CdMVCESxiI8uC",
    fields: [
      { name: "Tool_Name", id: "fldevlAFMGyyd2rK1", type: "singleLineText" },
      { name: "Status", id: "fldgiDOnVjszOfHUS", type: "singleLineText" },
      { name: "Duration_Ms", id: "fldBTb6d3pVskQMX0", type: "number" },
      { name: "Logged_At", id: "fld16TkAm54ygAOLV", type: "dateTime" },
    ],
  },
  ROOFING_INTELLIGENCE_SNAPSHOT: {
    tableId: "tblUFEep2vwND2jhZ",
    fields: [
      { name: "Label", id: "fldprVKrdWXSuTjhK", type: "singleLineText" },
      { name: "Captured_At", id: "fldtc7q7DJyYncgNG", type: "dateTime" },
      { name: "Accuracy_Rate_Pct", id: "fldrjqrouLsz9pqXb", type: "number" },
      { name: "Completed_Jobs", id: "fldk4TxPSKNPNJFK3", type: "number" },
      { name: "Avg_Confidence", id: "fldaMKvvk5cvCGPN3", type: "number" },
      { name: "Confidence_Trajectory", id: "fldlcLbnxIR6beC7r", type: "singleSelect" },
      { name: "Gaps_Json", id: "fldNeITp5CX6o38J8", type: "multilineText" },
    ],
  },
  ROOFING_CORRECTIONS: {
    tableId: "tblnScQSEWvNzkMST",
    fields: [
      { name: "Dimension", id: "fld6O4CvLj8FZwCNs", type: "singleLineText" },
      { name: "Suburb", id: "fldiSzjaoTV6rthmO", type: "singleLineText" },
      { name: "AI_Value", id: "fldnyI5ArgbRWKJfH", type: "number" },
      { name: "Human_Value", id: "fldkf56YnZ1vfktPX", type: "number" },
      { name: "Variance_Pct", id: "fldadkT8Ff51y88KO", type: "number" },
      { name: "Root_Cause", id: "fldqDgspinpJfyjB2", type: "multilineText" },
      { name: "Created_At", id: "fldheXf5rtocznjLG", type: "dateTime" },
    ],
  },
  ROOFING_HYPOTHESES: {
    tableId: "tblS9TjsVAfOmmR5i",
    fields: [
      { name: "Description", id: "fldFoCsox7IYfCrXE", type: "singleLineText" },
      { name: "Sample_Count", id: "fldicCIhFUR3Duago", type: "number" },
      { name: "Avg_Variance_Pct", id: "fldv1Lw0BlgIQeMal", type: "number" },
      { name: "Confidence", id: "fldNdFgky46hFoD9H", type: "number" },
      { name: "Status", id: "fldlKqha5JCUToNeP", type: "singleSelect" },
    ],
  },
  ROOFING_LEARNING_RULES: {
    tableId: "tblAo76JsN6r9ppSu",
    fields: [
      { name: "Rule_Code", id: "fldkDldCy1GdDfGUO", type: "singleLineText" },
      { name: "Category", id: "fldtOSGmQjmGqEOIA", type: "singleLineText" },
      { name: "Description", id: "fldePkqsdHJWzDeqF", type: "multilineText" },
      { name: "Trigger_Condition", id: "fld4KdYz5H5rT8mTT", type: "singleLineText" },
      { name: "Priority", id: "fld8heqmnj74QW6pA", type: "number" },
      { name: "Confidence", id: "fldRrkRp1g8nifKV0", type: "number" },
      { name: "Times_Triggered", id: "fldNbyrJWS1Cur8s8", type: "number" },
      { name: "Is_Active", id: "fldZgNrUm4jfljN3D", type: "checkbox" },
      { name: "Auto_Apply", id: "fldyLjIQqwGoWoeN3", type: "checkbox" },
    ],
  },
  ROOFING_QUOTES: {
    tableId: "tblnmk0xr8dTkyPBT",
    fields: [
      { name: "Ref_Number", id: "fldmjrrq6BfcnwKnA", type: "singleLineText" },
      { name: "Property_Address", id: "fld1EyGvRQJZl6Qvz", type: "singleLineText" },
      { name: "Contact_Name", id: "fld6PPOqv8KpqfNel", type: "singleLineText" },
      { name: "Status", id: "flduEvaFwFtGtf8CP", type: "singleSelect" },
      { name: "Material", id: "fldzuGLJw9ixnJwZP", type: "singleLineText" },
      { name: "Flat_Area_Sqm", id: "fldt57y73xPh8EJNi", type: "number" },
      { name: "Pitch_Type", id: "fld2pkYSO9pLK3Lx0", type: "singleLineText" },
      { name: "Total", id: "fldpA63pB56J4iCyz", type: "currency" },
      { name: "Created_At", id: "fldBCQeo6pS0G15UK", type: "dateTime" },
      { name: "ROOFING_QUOTE_ITEMS", id: "fldssEqwh6OD5Bq96", type: "multipleRecordLinks" },
      { name: "Waste_Factor_Pct", id: "fldhZWUGnO4YF5xbU", type: "number" },
      { name: "Pricing_Mechanism", id: "fldX7naut78mk4TbM", type: "singleLineText" },
      { name: "Pricing_Mode", id: "fldGlqJUjEub8oYoq", type: "singleLineText" },
      { name: "Package_Tier", id: "fldjYMXY71igXTpjH", type: "singleLineText" },
      { name: "Notes", id: "fldH98B4veHYpDltI", type: "multilineText" },
      { name: "Roof_Polygon_Json", id: "fldvpxKfveY0lzLSO", type: "multilineText" },
      { name: "Updated_At", id: "fldl4FJiesNfdm2V9", type: "dateTime" },
      { name: "Contact_Company", id: "fldIgTN9Ivld6POXy", type: "singleLineText" },
      { name: "Contact_Email", id: "fldIv6yU9o5uK6svX", type: "email" },
      { name: "Ridge_Lm", id: "fld7QkjuHXwZairfz", type: "number" },
      { name: "Eave_Lm", id: "fldEaHJZm07Qu7voY", type: "number" },
      { name: "Valley_Lm", id: "fldi7l5QYs4HXAqGX", type: "number" },
      { name: "Hip_Lm", id: "fldUEVjjjz0ZtfQOX", type: "number" },
      { name: "Rake_Lm", id: "fld0l9p3gLgGjN6CP", type: "number" },
      { name: "Pitch_Deg_Actual", id: "fldh9A1LArA9faSTe", type: "number" },
      { name: "Storeys", id: "fld26L9swzxAjSvoW", type: "number" },
      { name: "Roof_Colour", id: "fld5aJVYVBqsyVxw0", type: "singleLineText" },
      { name: "Contact_Phone", id: "fld9jV9W5b1TR0i1H", type: "singleLineText" },
    ],
  },
  ROOFING_QUOTE_ITEMS: {
    tableId: "tbla6UnVfACv98gpf",
    fields: [
      { name: "Description", id: "fldI2H77Y84Yiqv7s", type: "singleLineText" },
      { name: "Quantity", id: "fldJLLeHWTVFVAHPq", type: "number" },
      { name: "Unit", id: "fldxEQGbqj55SYBHb", type: "singleLineText" },
      { name: "Unit_Price_Ex_GST", id: "fldpdBF4Yn5QTymXc", type: "currency" },
      { name: "Sort_Order", id: "fldnCXMusSnXHrx3E", type: "number" },
      { name: "Quote", id: "fldfzAv6b8ximbX6w", type: "multipleRecordLinks" },
    ],
  },
  ROOFING_CONDITION_REPORTS: {
    tableId: "tbljHjUGT4kM0yGZA",
    fields: [
      { name: "Report_Number", id: "fldefjEphbWg2Gqy2", type: "singleLineText" },
      { name: "Client_Name", id: "fldqn5E5B6xwto21B", type: "singleLineText" },
      { name: "Condition_Grade", id: "fld0BKN862hivatJZ", type: "singleLineText" },
      { name: "Urgency_Level", id: "fldtY1VHsAEieUwWu", type: "singleLineText" },
      { name: "Status", id: "fldLcfrrI0YlDhXZR", type: "singleSelect" },
      { name: "Price_Ex_GST", id: "fldJrnytQdb3h9Tf3", type: "currency" },
      { name: "Generated_At", id: "fldHh434HeoGUKNuL", type: "dateTime" },
      { name: "Condition_Score", id: "fldHlW80YthTmsFdj", type: "number" },
      { name: "Life_Remaining_Years", id: "fldilyd0HBovqlcjK", type: "number" },
      { name: "AI_Assessment", id: "fldDbqQWPBmoVxEi2", type: "multilineText" },
      { name: "Recommended_Works", id: "fldbyzo4UNEsHHpJt", type: "multilineText" },
      { name: "Report_Type", id: "fldFxM9JktWSi5CDq", type: "singleLineText" },
      { name: "Inspector_Name", id: "fldGU74rPvzxQbuSD", type: "singleLineText" },
    ],
  },
  ROOFING_PURCHASE_ORDERS: {
    tableId: "tblr6R3zdvJ0Thidw",
    fields: [
      { name: "PO_Number", id: "fldd547rwmwybAvUC", type: "singleLineText" },
      { name: "Vendor_Name", id: "flduJBveemDQvvSsa", type: "singleLineText" },
      { name: "Status", id: "fldzkLma95Y0teM8p", type: "singleSelect" },
      { name: "Total", id: "fldxfFeFtrgXMIYLo", type: "currency" },
      { name: "Created_At", id: "fldAzR8egROejzJmE", type: "dateTime" },
      { name: "ROOFING_PO_ITEMS", id: "fldl5cZ6PK3KNxSnN", type: "multipleRecordLinks" },
      { name: "Delivery_Address", id: "fldOe49tC4xNhSFDY", type: "singleLineText" },
      { name: "Requested_Delivery_Date", id: "flduK5MfoZQ4cjipJ", type: "date" },
      { name: "Notes", id: "fldu3F7z67KVhmXYj", type: "multilineText" },
    ],
  },
  ROOFING_STORM_EVENTS: {
    tableId: "tblsmggD9abxBBxoY",
    fields: [
      { name: "Name", id: "fld2LKTWObYYXJKPi", type: "singleLineText" },
      { name: "Event_Type", id: "fldgVllSJJsKjKN5O", type: "singleLineText" },
      { name: "Event_Date", id: "fld0DgK18rwzFs3ed", type: "date" },
      { name: "State", id: "fldGxUZqHKZ6YGXg6", type: "singleLineText" },
      { name: "Leads_Count", id: "fldcuSYiAQSa2hnx9", type: "number" },
      { name: "Severity", id: "fldKkcCA5xOITwFP9", type: "number" },
      { name: "Affected_Suburbs", id: "fld4Uii0geTJRGUPX", type: "multilineText" },
      { name: "ROOFING_STORM_LEADS", id: "fldSN5iCzqfZElk30", type: "multipleRecordLinks" },
    ],
  },
  ROOFING_MEASUREMENT_SNAPSHOTS: {
    tableId: "tblWvJuMi13rPCHgj",
    fields: [
      { name: "Address", id: "fldj2uzxJ9fhEcjL3", type: "singleLineText" },
      { name: "Total_Area_M2", id: "fldoMvsTYOU6tJG7e", type: "number" },
      { name: "Section_Count", id: "fldYXxThCW0MFM3G3", type: "number" },
      { name: "Storeys", id: "fldoJWmeXFFh1gHrd", type: "number" },
      { name: "Snapshot_Type", id: "fld7ohXulN2OV7xLJ", type: "singleLineText" },
      { name: "Created_At", id: "fldm4bfGqQse0zCQo", type: "dateTime" },
    ],
  },
  ROOFING_QUOTE_SNAPSHOTS: {
    tableId: "tbl0YQUof4R3HTdsS",
    fields: [
      { name: "Address", id: "fldw9sKTqlXGcHCiV", type: "singleLineText" },
      { name: "Roof_Type", id: "fldO3M4AXPqDxeWKk", type: "singleLineText" },
      { name: "Total_Inc_GST", id: "flditXGlMSNXb3OwF", type: "currency" },
      { name: "Created_At", id: "fldvtT83tBmgbgoz3", type: "dateTime" },
    ],
  },
  ROOFING_STORM_LEADS: {
    tableId: "tbla4s1t0KwiS2m9G",
    fields: [
      { name: "Address", id: "fld8lwLHPXZ9wrour", type: "singleLineText" },
      { name: "Suburb", id: "fld0TIpogtgG99hNI", type: "singleLineText" },
      { name: "Roof_Area_Sqm", id: "fldZIlPYr3010XUBc", type: "number" },
      { name: "Estimated_Value", id: "fldjMeQQ9IUi3Mdrj", type: "currency" },
      { name: "Contact_Name", id: "fldiSHiZX3spLmr4H", type: "singleLineText" },
      { name: "Contact_Phone", id: "fldOiGN69qFPxIBPV", type: "singleLineText" },
      { name: "Status", id: "fld82G5f0Ph1KsXnD", type: "singleSelect" },
      { name: "Storm_Event", id: "fldfgUvxnw0LGS1uw", type: "multipleRecordLinks" },
    ],
  },
  ROOFING_PO_ITEMS: {
    tableId: "tblWY0FuPiPEsIFLc",
    fields: [
      { name: "Description", id: "fldTsELSee0wvyMeB", type: "singleLineText" },
      { name: "Quantity", id: "fldpPvSOCA3LoH8QH", type: "number" },
      { name: "Unit", id: "fld0uxcZ9qH1aXBpH", type: "singleLineText" },
      { name: "Unit_Price_Ex_GST", id: "fldBQvxNCg4CEEvUj", type: "currency" },
      { name: "Sort_Order", id: "fldf6RAU29kQOXo3R", type: "number" },
      { name: "Purchase_Order", id: "fldaf19v1tGKZeqTB", type: "multipleRecordLinks" },
    ],
  },
} as const;

export type CoreTableName = keyof typeof CORE_SCHEMA;
