import { cookies } from "next/headers";
import Link from "next/link";
import { prisma as db } from "@/lib/db";
import { PageHeader, MetricCard, StatusBadge } from "@/components/PageHeader";
import { formatDate } from "@/lib/format";

export const dynamic = "force-dynamic";

export default async function ReportsPage() {
  let reports: Awaited<ReturnType<typeof db.uc3WeeklyReport.findMany>> = [];

  try {
    const cookieStore = await cookies();
    const val = cookieStore.get("uc3_tenant_id")?.value;
    let tenantId: number | null = val ? Number(val) : null;
    if (!tenantId) {
      const fallback = await db.uc3Tenant.findFirst({
        where: { isActive: true },
        orderBy: { id: "asc" },
        select: { id: true },
      });
      tenantId = fallback?.id ?? null;
    }
    if (tenantId) {
      reports = await db.uc3WeeklyReport.findMany({
        where: { tenantId },
        orderBy: { weekEnding: "desc" },
        include: { project: { select: { name: true } } },
      });
    }
  } catch {
    // graceful empty state
  }

  const total = reports.length;
  const drafts = reports.filter((r) => r.status === "draft").length;
  const approved = reports.filter((r) => r.status === "approved").length;
  const sent = reports.filter((r) => r.status === "sent").length;
  const aiGenerated = reports.filter((r) => r.isAiGenerated).length;

  return (
    <div className="pb-16">
      <PageHeader
        title="Weekly Reports"
        subtitle="AI-generated and manual weekly project reports"
        actions={[{ href: "/uc3/reports/generate", label: "+ Generate Report" }]}
      />

      <div className="px-8 space-y-6">
        <div className="grid grid-cols-2 sm:grid-cols-4 gap-4">
          <MetricCard value={total} label="Total Reports" />
          <MetricCard value={drafts} label="Drafts" />
          <MetricCard value={approved} label="Approved" />
          <MetricCard value={sent} label="Sent" />
        </div>

        <div className="ae-card overflow-hidden">
          {reports.length === 0 ? (
            <div className="p-6 text-neutral-500 text-sm">
              No reports yet.{" "}
              <Link href="/uc3/reports/generate" className="text-blue-600 underline">
                Generate the first one.
              </Link>
            </div>
          ) : (
            <table className="ae-table w-full">
              <thead>
                <tr>
                  <th>Title</th>
                  <th>Project</th>
                  <th>Week Ending</th>
                  <th>Source</th>
                  <th>Status</th>
                  <th>Generated At</th>
                  <th></th>
                </tr>
              </thead>
              <tbody>
                {reports.map((r) => (
                  <tr key={r.id}>
                    <td className="font-medium">
                      <Link href={`/uc3/reports/${r.id}`} className="text-blue-600 hover:underline">
                        {r.title}
                      </Link>
                    </td>
                    <td>
                      {(r as typeof r & { project?: { name: string } | null }).project?.name ?? "—"}
                    </td>
                    <td>{formatDate(r.weekEnding)}</td>
                    <td>
                      {r.isAiGenerated ? (
                        <span className="inline-flex items-center gap-1 px-2 py-0.5 rounded-full text-xs font-medium bg-purple-100 text-purple-700">
                          ✦ AI
                        </span>
                      ) : (
                        <span className="inline-flex items-center px-2 py-0.5 rounded-full text-xs font-medium bg-neutral-100 text-neutral-600">
                          Manual
                        </span>
                      )}
                    </td>
                    <td>
                      <StatusBadge status={r.status} />
                    </td>
                    <td className="text-neutral-500 text-sm">
                      {r.generatedAt ? formatDate(r.generatedAt) : "—"}
                    </td>
                    <td>
                      <Link
                        href={`/uc3/reports/${r.id}`}
                        className="btn-ae-outline text-xs py-1 px-3"
                      >
                        View
                      </Link>
                    </td>
                  </tr>
                ))}
              </tbody>
            </table>
          )}
        </div>

        {aiGenerated > 0 && (
          <p className="text-xs text-neutral-400">
            ✦ {aiGenerated} report{aiGenerated !== 1 ? "s" : ""} generated by AI
          </p>
        )}
      </div>
    </div>
  );
}
